### PR TITLE
Versions change: Change api version to v1alpha1

### PR DESCRIPTION
**Pull request by nirarg**
Decrease capk version to v1alpha1

### CODE REVIEW

**Review by cchengleo — COMMENTED** [review]
/ok-to-test

**Comment by cchengleo** [comment]
It seems `clusterctl` does not honor older v1alpha1 providers anymore. It fails out integration e2e CI:

```
$ cluster-api/bin/clusterctl version

clusterctl version: &version.Info{Major:"0", Minor:"4", GitVersion:"v0.4.4-dirty", GitCommit:"d50c55d5df741b0c61834bcc1802451d80e6c200", GitTreeState:"dirty", BuildDate:"2021-12-20T10:25:07Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/amd64"}
```

```
clusterctl init \
   --core cluster-api:v0.4.99 \
   --bootstrap kubeadm:v0.4.99 \
   --control-plane kubeadm:v0.4.99 \
   --infrastructure kubevirt:v0.1.0 \
   --config ~/.cluster-api/dev-repository/config.yaml

go build -ldflags "-X 'sigs.k8s.io/cluster-api/version.buildDate=2021-12-20T10:25:07Z' -X 'sigs.k8s.io/cluster-api/version.gitCommit=d50c55d5df741b0c61834bcc1802451d80e6c200' -X 'sigs.k8s.io/cluster-api/version.gitTreeState=dirty' -X 'sigs.k8s.io/cluster-api/version.gitMajor=0' -X 'sigs.k8s.io/cluster-api/version.gitMinor=4' -X 'sigs.k8s.io/cluster-api/version.gitVersion=v0.4.4-dirty' -X 'sigs.k8s.io/cluster-api/version.gitReleaseCommit=d50c55d5df741b0c61834bcc1802451d80e6c200'" -o bin/clusterctl sigs.k8s.io/cluster-api/cmd/clusterctl
go: downloading cloud.google.com/go v0.81.0
go: downloading github.com/form3tech-oss/jwt-go v3.2.3+incompatible
go: downloading k8s.io/kubectl v0.21.4
go: downloading github.com/spf13/viper v1.8.1
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/drone/envsubst/v2 v2.0.0-20210615175204-7bf45dbf5372
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading gopkg.in/ini.v1 v1.62.0
go: downloading github.com/pelletier/go-toml v1.9.3
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/mitchellh/mapstructure v1.4.1
Fetching providers
Error: current version of clusterctl is only compatible with v1alpha4 providers, detected v1alpha1 for provider infrastructure-kubevirt
```
@rmohr, are you guys using clusterctl in e2e?

**Comment by cchengleo** [comment]
> It seems `clusterctl` does not honor older v1alpha1 providers anymore. It fails out integration e2e CI:
> 
> ```
> $ cluster-api/bin/clusterctl version
> 
> clusterctl version: &version.Info{Major:"0", Minor:"4", GitVersion:"v0.4.4-dirty", GitCommit:"d50c55d5df741b0c61834bcc1802451d80e6c200", GitTreeState:"dirty", BuildDate:"2021-12-20T10:25:07Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/amd64"}
> ```
> 
> ```
> clusterctl init \
>    --core cluster-api:v0.4.99 \
>    --bootstrap kubeadm:v0.4.99 \
>    --control-plane kubeadm:v0.4.99 \
>    --infrastructure kubevirt:v0.1.0 \
>    --config ~/.cluster-api/dev-repository/config.yaml
> 
> go build -ldflags "-X 'sigs.k8s.io/cluster-api/version.buildDate=2021-12-20T10:25:07Z' -X 'sigs.k8s.io/cluster-api/version.gitCommit=d50c55d5df741b0c61834bcc1802451d80e6c200' -X 'sigs.k8s.io/cluster-api/version.gitTreeState=dirty' -X 'sigs.k8s.io/cluster-api/version.gitMajor=0' -X 'sigs.k8s.io/cluster-api/version.gitMinor=4' -X 'sigs.k8s.io/cluster-api/version.gitVersion=v0.4.4-dirty' -X 'sigs.k8s.io/cluster-api/version.gitReleaseCommit=d50c55d5df741b0c61834bcc1802451d80e6c200'" -o bin/clusterctl sigs.k8s.io/cluster-api/cmd/clusterctl
> go: downloading cloud.google.com/go v0.81.0
> go: downloading github.com/form3tech-oss/jwt-go v3.2.3+incompatible
> go: downloading k8s.io/kubectl v0.21.4
> go: downloading github.com/spf13/viper v1.8.1
> go: downloading github.com/mattn/go-runewidth v0.0.13
> go: downloading github.com/drone/envsubst/v2 v2.0.0-20210615175204-7bf45dbf5372
> go: downloading github.com/rivo/uniseg v0.2.0
> go: downloading gopkg.in/ini.v1 v1.62.0
> go: downloading github.com/pelletier/go-toml v1.9.3
> go: downloading github.com/spf13/cast v1.3.1
> go: downloading github.com/mitchellh/mapstructure v1.4.1
> Fetching providers
> Error: current version of clusterctl is only compatible with v1alpha4 providers, detected v1alpha1 for provider infrastructure-kubevirt
> ```
> 
> @rmohr, are you guys using clusterctl in e2e?

Seems the `e2e / integration` CI from KubeVirt is using v0.4.4 clusterctl and loaded the with default version (v0.4.5) of providers.

**Comment by rmohr** [comment]
> Seems the `e2e / integration` CI from KubeVirt is using v0.4.4 clusterctl and loaded the with default version (v0.4.5) of providers.

Yes that is what we use: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/main/kubevirtci#L38

**Comment by rmohr** [comment]
@cchengleo the e2e test is passing now. did you try it yourself with 0.4.5 or where did you make the observation?

**Review by cchengleo — APPROVED** [review]
I have verified the change with v0.4.5 CAPI release. There is a minor status reporting issue of `clusterctl` not related to this PR:

```
NAME                                                                 READY  SEVERITY  REASON                       SINCE  MESSAGE
/workload-cluster                                                    True                                          4m43s
├─ClusterInfrastructure - KubevirtCluster/workload-cluster           True                                          7m21s
├─ControlPlane - KubeadmControlPlane/workload-cluster-control-plane  True                                          4m43s
│ └─Machine/workload-cluster-control-plane-vq9k4                     True                                          4m44s
└─Workers
  └─MachineDeployment/workload-cluster-md-0                          False  Warning   WaitingForAvailableMachines  7m17s  Minimum availability requires 1 replicas, current 0 available
    └─Machine/workload-cluster-md-0-799ddd6f64-pkw6d                 True                                          3m23s
```

**Pull request merged**
