### PR TITLE
Updated metadata.yaml major version to 0 to fix clusterctl problem

### PR DESCRIPTION
**Pull request by isaacdorfman**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release notes**:

```release-note
```

### CODE REVIEW

**Comment by isaacdorfman** [comment]
@davidvossel

**Comment by isaacdorfman** [comment]
@davidvossel 

P.S: metadata.yaml does not contain a patch version field.
It assumes the patch version from the release tag.

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
