### PR TITLE
Update to golang 1.20

### PR DESCRIPTION
**Pull request by davidvossel**
updates to use golang 1.20.6, the latest stable golang release

### CODE REVIEW

**Comment by agradouski** [comment]
@davidvossel looks like `build / check-gen` check is failing

**Comment by agradouski** [comment]
otherwise /lgtm

**Comment by agradouski** [comment]
otherwise,
/lgtm

**Comment by nunnatsa** [comment]
@davidvossel - I missed this PR. Sorry. done in #257 

/close

**Pull request closed without merging**
