### PR TITLE
Bump k8s.io/client-go to v0.28.2

### PR DESCRIPTION
**Pull request by bryan-cox**
**What this PR does / why we need it**:
Bump k8s.io/client-go to v0.28.2

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
can this bump be done without including the vendor dir? `make modules` is what we usually run after modifying the go.mod file.

**Comment by nunnatsa** [comment]
LGTM in general. One question - do we want to bump everything to `v0.28.3`? I think it fixes the http2 CVE.

**Comment by bryan-cox** [comment]
> LGTM in general. One question - do we want to bump everything to `v0.28.3`? I think it fixes the http2 CVE.

Yeah it looks like it - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md#changelog-since-v1282

I'll bump things up.

**Comment by davidvossel** [comment]
i re-kicked off the e2e tests

**Comment by davidvossel** [comment]
e2e tests are failing due to a go mod change.
```
go: updates to go.mod needed; to update it:
	go mod tidy
make[1]: *** [Makefile:106: build-e2e-test] Error 1
```

i guess run go mod tidy? maybe something needs to be updated

**Comment by bryan-cox** [comment]
> e2e tests are failing due to a go mod change.
> 
> ```
> go: updates to go.mod needed; to update it:
> 	go mod tidy
> make[1]: *** [Makefile:106: build-e2e-test] Error 1
> ```
> 
> i guess run go mod tidy? maybe something needs to be updated

Ok, I did that and it updated the go.mod in the e2e directory. Weird, I thought `make modules` ran `go mod tidy` already.

**Pull request merged**
