### PR TITLE
Create coverage file on unit test in CI

### PR DESCRIPTION
**Pull request by nunnatsa**
Later we can decide if to publish it (e.g. to [coveralls.io](https://coveralls.io))

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release notes**:

```release-note
None
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
@cchengleo in order to let coveralls comment on the repo, we need a maintainer to follow the steps in this link: 
https://docs.coveralls.io/coveralls-notifications. 

Would you like to do that?

**Comment by nunnatsa** [comment]
Close and reopen to terun the e2e test.

**Review by cchengleo — APPROVED** [review]
/lgtm

**Pull request merged**
