### PR TITLE
Cluster deletion race

### LINKED ISSUE #65: cluster teardown hangs
/kind bug

A kubevirt provider cluster should be able to be torn down by deleting the top level Cluster object, however that doesn't work today.

The issue is that the KubeVirtMachine objects will never have their finalizer removed during the cascading deletion if the top level Cluster object get's deleted before the KubeVirtMachines can be processed.

The result is that the KubeVirtMachine objects block indefinitely trying to get the non-existent Cluster object as a precondition to processing the deletion and removing the finalizer. This blocks the cluster from being torn down entirely.

### PR DESCRIPTION
**Pull request by davidvossel**
Fixes #65 

# Overview
A KubevirtMachine object should be able to successfully terminate and be removed regardless if the cooresponding Cluster or KubevirtCluster object exists.

Today, we have no strong guarantee that a corresponding KubevirtCluster will still exist when a KubevirtMachine is being torn down. If the kv cluster object disappears before the kv machine, the machine controller will block indefinitely waiting for the kv cluster object to be accessible before processing the kv machine's deletion.

# Steps to Reproduce

Delete a KubevirtCluster's namespace and the kubevirt machines will block the namespace from being terminated indefinitely.

# Fix Explanation

The KubevirtMachine objects depended on the KubevirtCluster in order to retrieve a reference to a secret that represents the kubeconfig used to create/delete VMs.  If the KubevirtCluster disappears before the KubevirtMachine, then the kv machine can not process the VM deletion accurately because it doesn't know the secret ref to use.

To fix this, the KubevirtMachine object now stores the secret ref itself on its spec in the `KubevirtMachine.Spec.InfraClusterSecretRef ` field similar to the KubevirtCluster. This value will default to the cluster's secret ref when nil, which preserves existing behavior.

By storing the secret ref on the kv machine itself, the machine can be torn down independently of whether or not the kv cluster still exists.

# Alternate solutions

An alternate solution to this that was given consideration was to put a finalizer on the KubevirtCluster object and not allow it to be deleted until all corresponding KubevirtMachines are gone. The problem with this is KubevirtCluster's which are externally managed outside of the capk controllers #79. When a KubevirtCluster is externally managed, the capk controller won't reconcile it, which means we don't maintain control over a finalizer or it's usage.

```release-note
Fixes race condition between kubevirtcluster and kubevirtmachine during tear down
```

### CODE REVIEW

**Comment by davidvossel** [comment]
/hold
/cc @agradouski 

@agradouski  This impacts your use case for launching tenant clusters external to the capk management cluster. It would be good to have your eyes on this.

I feel like I had to take an unfortunately long path to decouple the KubevirtCluster and KubevirtMachine from one another during tear down here. The obvious solution to me would have been to use a finalizer on the KubevirtCluster and ensure it doesn't disappear until all corresponding KubevirtMachine's are gone, but #79 makes that complicated. Basically there are scenarios where the KubevirtCluster isn't managed by capk that we have to consider now, which makes depending on a finalizer difficult.

**Comment by agradouski** [comment]
@davidvossel the code change makes sense, but I'm curious to learn more about the use case when KubevirtCluster isn't managed by CAPK. let's discuss in the next CAPK community meeting.

**Comment by Arvinderpal** [comment]
@davidvossel I'm having a hard time grasping the motivation for this. Please share any additional docs you may have on this. Also, if other providers are supporting this behavior (e.g. aws) then please share links.

**Comment by davidvossel** [comment]
@agradouski @Arvinderpal 

Here's more info.

# Community discussion links

**[Externally managed Cluster Design Proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210203-externally-managed-cluster-infrastructure.md)** This document describes the use case for externally managed clusters

**[Cluster-api Issue:](https://github.com/kubernetes-sigs/cluster-api/issues/4095)**  This describes the initial use case and motivation for the change.

**[AWS Provider Implementation](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2383 )** This shows how the aws provider implements this feature. This is ultimately what we're trying to copy for capk

Here's a snippet regarding the use case

_"As a CAPI consumer I'd like to plug-in my own ControlPlane and Infrastructure resources [1] while still still reusing the existing machine controller implementation for infra providers. Today this is not possible in some providers because the machine controllers are tightly coupled with the regular AWS/AzureCluster kind."_

# cluster object example

Below is an example `cluster` created by our hypershift controller. As you can see, we're creating a KubeVirtCluster object just like you'd normally expect. the difference here is that the KubevirtCluster is reconciled by hypershift rather than capk... So hypershift is creating the load balancer for the cluster api server and everything else involved with the provider's cluster object.

The KubeVirtMachine objects are managed by CAPK like we'd expect though.

```
apiVersion: cluster.x-k8s.io/v1beta1
  kind: Cluster
  metadata:
    annotations:
      hypershift.openshift.io/cluster: clusters/test-cluster
    name: test-cluster-4zzhg
    namespace: clusters-test-cluster
  spec:
    controlPlaneEndpoint:
      host: ""
      port: 0
    controlPlaneRef:
      apiVersion: hypershift.openshift.io/v1alpha1
      kind: HostedControlPlane
      name: test-cluster
      namespace: clusters-test-cluster
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtCluster
      name: test-cluster-4zzhg
      namespace: clusters-test-cluster
```

**Comment by agradouski** [comment]
thanks for sharing additional context @davidvossel

**Pull request merged**
