### PR TITLE
Meeting Details

### LINKED ISSUE #29: Add the weekly meeting schedule in the `office hours` section
Currently the `README.md` doesn't mention the weekly meetings for Kubevirt as we can see here: https://github.com/kubernetes/community/blob/master/sig-cluster-lifecycle/README.md#cluster-api-provider-kubevirt
So, it would be better if we could add the weekly meetings in the `office-hours` section.

**Environment:**

- Cluster-api version: 
- Cluster-api-provider-kubevirt version: 
- Kubernetes version: (use `kubectl version`): 
- KubeVirt version:
- OS (e.g. from `/etc/os-release`):

/kind documentation
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by aaseem**
**Added the weekly meeting schedule in the office hours section**:

**Meeting schedule is missing in the README.md** *(optional, in `fixes #29 ` format, will close that issue when PR gets merged)*: fixes #29 

**Special notes for your reviewer**:  Please review 

**Release notes**:

```release-note
```

### CODE REVIEW

**Comment by aaseem** [comment]
I have signed CLA

**Comment by sayantani11** [comment]
@aaseem The issue was already taken by someone else, and it works on first come first

**Comment by sayantani11** [comment]
@aaseem Can you make another PR for this?

**Comment by aaseem** [comment]
Yes ,sure. Create below one

https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/52

**Pull request closed without merging**
