### PR TITLE
[Initial implementation migration] Add clusterctl-settings and metadata file

### PR DESCRIPTION
**Pull request by cchengleo**
**What this PR does / why we need it**:
Add clusterctl-settings and add metadata for cluster-api contract version

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
N/A

**Special notes for your reviewer**:
N/A

**Release notes**:

```release-note
N/A
```

### CODE REVIEW

**Review by agradouski — APPROVED** [review]
/lgtm

**Comment by neolit123** [comment]
Looks like retest is not triggering the tide check.
You could push a new commit on top and then remove it to try to retrigger.

For help you can ask in #sig-testing on slack.

**Comment by cchengleo** [comment]
> /retest
> 
> Tide is the tool reponsible for merging lgtm/approve prs. It creates a merge commit for each pr.
> 
> The repo did not allow merge commits, so i allowed that in the settings. Clicking the merge button is generally discouraged unless necessary.

I would prefer the `squash merging` than `merge` so that we could keep a clean history.

**Pull request merged**
