### PR TITLE
Limit github action to run only on the kubernetes-sigs/cluster-api-provider-kubevirt repository

### PR DESCRIPTION
**Pull request by nunnatsa**
Add a condition to the github action, to prevent them to run on another repositories, like forks.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**What this PR does / why we need it**:
We don't want the github action to run on forks of this repository. This PR prevents that.

**Special notes for your reviewer**:

**Release notes**:

```release-note
None
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
I signed it

**Comment by rmohr** [comment]
@nunnatsa the PR looks great. However the normal unit tests were not triggered. I could not find any mistake in the action, but maybe you can have another look and see why they don't get triggered?

**Comment by rmohr** [comment]
Oh @nunnatsa it is probably fine, but someone has to click the "approve and run" button it seems. @cchengleo FYI.

**Review by cchengleo — APPROVED** [review]
@nunnatsa the PR looks great!

/lgtm

**Pull request merged**
