### PR TITLE
Add sentinel bootstrap file check modes in CRD

### PR DESCRIPTION
**Pull request by BarthV**
https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/233

### CODE REVIEW

**Comment by agradouski** [comment]
should we include this in kubevirtmachine spec explicitly as part of this PR, given that default value is "ssh" anyway:
```
virtualMachineBootstrapCheck:
         checkStrategy: ssh
```
I know we made it backward compatible, and this is not required in the template, asking more wrt potentially confusing existing users.

one advantage of making it explicit is perhaps giving users heads up about changes (current and future) in that part of logic.

@davidvossel @pjaton  wdyt?

**Review by pjaton — APPROVED** [review]
Thanks @BarthV , LGTM 👍

**Comment by pjaton** [comment]
> should we include this in kubevirtmachine spec explicitly as part of this PR, given that default value is "ssh" anyway:
> 
> ```
> virtualMachineBootstrapCheck:
>          checkStrategy: ssh
> ```
> 
> I know we made it backward compatible, and this is not required in the template, asking more wrt potentially confusing existing users.
> 
> one advantage of making it explicit is perhaps giving users heads up about changes (current and future) in that part of logic.
> 
> @davidvossel @pjaton wdyt?

In this case, I feel that the expected behavior by most users is really about "please use the default mechanism"; so, using unset to mean default feels more intuitive to me than making this required. I do see your point about future change, though, I simply see that there would be more impact if this is made required.

**Review by agradouski — APPROVED** [review]

**Pull request merged**
