### PR TITLE
owners: Add Quique as owners to some sub directories

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:

Add Quique as approvers to select directories

**Release notes**:

```release-note
NONE
```

### CODE REVIEW

**Comment by davidvossel** [comment]
@qinqon you all will need to become members of the kubernetes-sig org first. You'll need two sponsors from separate companies to do this. I can sponsor you, but you'll need one more. Follow the directions here, https://github.com/kubernetes/community/blob/master/community-membership.md#member

**Comment by qinqon** [comment]
> @qinqon you all will need to become members of the kubernetes-sig org first. You'll need two sponsors from separate companies to do this. I can sponsor you, but you'll need one more. Follow the directions here, https://github.com/kubernetes/community/blob/master/community-membership.md#member

Done https://github.com/kubernetes/org/issues/3740

**Comment by davidvossel** [comment]
@qinqon can you update this PR to just have your name added to the approvers since Radim isn't in the org yet, that way we can at least get you in now.

**Pull request merged**
