### PR TITLE
update README.md

### PR DESCRIPTION
**Pull request by TheAbhishekS**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release notes**:

```release-note
```

### CODE REVIEW

**Comment by jayesh-srivastava** [comment]
> **What this PR does / why we need it**:
> 
> **Which issue this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #
> 
> **Special notes for your reviewer**:
> 
> **Release notes**:

@TheAbhishekS Kindly mention the issue number which the PR fixes and edit the PR message for better readability. Try to look through other PRs for reference.

**Comment by jayesh-srivastava** [comment]
@TheAbhishekS What you changed is the commit message. That was okay. I am talking about the quoted text right here.


> **What this PR does / why we need it**:
> 
> **Which issue this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #
> 
> **Special notes for your reviewer**:
> 
> **Release notes**:

**Comment by TheAbhishekS** [comment]
> 

so u basically saying i should make another comment here and mention issue number and what file i changed

**Comment by jayesh-srivastava** [comment]
@TheAbhishekS No you can simply edit it and mention the issue number. No need to mention the files changed.

**Comment by TheAbhishekS** [comment]
> **What this PR does / why we need it**:
> 
> **Which issue this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes # 34
> 
> **Special notes for your reviewer**:
> 
> **Release notes**:

**Comment by TheAbhishekS** [comment]
> **What this PR does / why we need it**:
>there was a typo in line no.48  of README.md ,This change fix that typo
> **Which issue this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes # 34
> 
> **Special notes for your reviewer**:
> 
> **Release notes**:

**Comment by cchengleo** [comment]
Hi @TheAbhishekS,  do we still need this PR? If not, you could close it.

**Comment by TheAbhishekS** [comment]
@cchengleo done and sorry for the inconvenience

**Pull request closed without merging**
